### ISSUE TITLE
Giveaways Feature

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#110]
This feature would get rid of the need to use the GiveawayBot in the server, as it offers little in the way of customization and has features that are not needed.

In terms of automation, the bot needs to be able to automatically have a `Legacy Role` giveaway created in `#giveaways` for 1 week every week and assign the winners the Legacy role upon selection.

When creating a giveaway, a similar process to GiveawayBot would be ideal, with the addition of hours `h` and days `d` when choosing the length of the giveaway. I have attached screenshots of the current process with the GiveawayBot. Only admin and dev should be able to create giveaways.
![screen shot on 2018-01-28 at 12_50_06](https://user-images.githubusercontent.com/27379200/35485778-e71ea3f8-0429-11e8-9ba6-4237cb87ac49.png)
![screen shot on 2018-01-28 at 12_50_17](https://user-images.githubusercontent.com/27379200/35485784-ed1e5f82-0429-11e8-9917-a55ebad7ee70.png)

**Comment by coledeb** [comment]
@ThePjpollie We can work out details such as exact wording to use on each step etc. as we go along. This is how the current embed looks, I think a similar setup will work nicely for our bot. 
![screen shot on 2018-01-28 at 12_51_49](https://user-images.githubusercontent.com/27379200/35485800-24357280-042a-11e8-9c47-b305283a2fe6.png)

**Comment by ThePjpollie** [comment]
Do you want to decide the time yourself? I can automate it so it stops at a time (decided by you) and it starts it by itself again. So it'll announce the winners and instantly create a new giveaway for a week.

We can also imlement other giveaways features later then you can manually set it all. But I'm PURELY talking about the Legacy giveaway for this week. With sort off a "switch" you'll be able to disable the giveaway for a week if you want that

**Comment by coledeb** [comment]
@ThePjpollie Yeah legacy would only need a disable switch. It should automatically do a week every time unless stopped, and auto create / assign. The only thing that I dont think can be automated is the @Giveaways ping for the giveaway, but once we have settled into a routine I might not ping that role each week anyways

**Comment by ThePjpollie** [comment]
@HaydenMeloche these are things to add to db:
```
CREATE TABLE `misc` ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `function` TEXT, `value` TEXT )

INSERT INTO `misc` (function, value) VALUES ('giveawaymsg', '')
INSERT INTO `misc` (function, value) VALUES ('giveawaywinners', '[]')
INSERT INTO `misc` (function, value) VALUES ('giveawayon', '1')
```

**Comment by HaydenMeloche** [comment]
@ThePjpollie That table already exists and was seeming to throw errors when I tried the insert code

**Comment by ThePjpollie** [comment]
Owh whoops, must have missed it then :o

**Comment by HaydenMeloche** [comment]
np :)
