### ISSUE TITLE
Partner channel revamp

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#112]
This would be a complete revamp of the partner category / channels in our server to clean up this mess.
![fac596c2371379ced8df65fd1adcd6b1](https://user-images.githubusercontent.com/27379200/35712781-79731376-0789-11e8-82ab-dd52f341c454.png)

The `#partners` channel and the individual org channels will be consolidated into one `#partners` channel, with reactions that give the information when clicked on.

I have attached two concepts, I'm leaning towards having images in the channel but having them shrunk greatly, I will need to create these images if we go through with that. No problem on that end.
![aa7cb755c6067af96a05889db3ed5d76](https://user-images.githubusercontent.com/27379200/35712871-faca8b84-0789-11e8-8bac-a6e31ec125be.png)

![e78b2f2cfc9206b866655e0096b0632b](https://user-images.githubusercontent.com/27379200/35712880-0df30c54-078a-11e8-91cd-450a993ad6a1.png)

@ThePjpollie I mentioned this earlier to you as a post v1 feature, would be great to start working on this soon as I'm working on revamping our current partners now.

**Comment by coledeb** [comment]
In terms of what the bot would return to the user's DMs when the reaction is clicked on, it would be ideal to have it spit out essentially the current partner channels. Will need to remake a few of the borders probably, and tidy up / unify some things. Attached a sample screenshot of a current partner channel below:
![71b7ea0ceb21b821e989c07a38c08dd9](https://user-images.githubusercontent.com/27379200/35713051-ebf4f88c-078a-11e8-9300-934e35fd9455.png)

**Comment by ThePjpollie** [comment]
I could make this, keeping in mind for new partners we'll need to change the code and bot needs to be updated.

**Comment by xNameless69** [comment]
In my opinion it would be easier to have a message with some kind of identifier that has the reaction on it,

For instance:
"Partner: RLMods" Separate message which would have a reaction on, on add reaction check args[0] for "Partner:", grab the rest as an identifier for which parner, and then have a file stored with the messages to send written in JSON.

`{
    "partners":[
        "RLMods": {
            messages: [
                "RLMods is a blah blah blah blah",
                "They are go to mods website blah blah"
            ]
        }
    ]
}` 

it can just get file["partners"][args[1]] and loop through sending the messages, not sure how sending images would work with said system, but it could then be just added to the config file as an additional parner in the array, and a message with "Partner: New Partner Name" sent into the channel with a reaction added.

**Comment by xNameless69** [comment]
# **Currently working on this feature**
_(don't have perms to assign or move it or whatever)_
