### ISSUE TITLE
External server roles / titles

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#134]
I have talked with Root about this possibility / concept before. Essentially how the bot's `#set-special-title` feature works now is that it allows access to set titles / colors based on a role that a person has in the discord.  A feature that would be amazing would be to have the bot able to be added to other servers. From there, being able to create "special titles" that are dependent on roles in these external servers that it was added to. 

Case Example: We were actually talking with Scrub Killa about this idea. He has the sub role synced in his Discord (at least I assume that he does now since he has actually made a Discord), and with this concept the bot would that role access to a special title / color (rather than having to add all of his subscribers to a role in our Discord).

This could be useful in a large amount of ways, from allowing staff members in other servers access to titles, to subscribers of twitch partners, to tourney winners in partner's servers.

**Comment by HaydenMeloche** [comment]
I think the best way is to have a bot sit in their discords with no perms. It can update a database we have than the AC bot can also link into

**Comment by ThePjpollie** [comment]
I would suggest having a different bot for that. Just to be sure in case smth goes wrong the the public one we have the official one running without a problem?

Second would I suggest to not let everyone be able to do it. So it shouldnt be a user input title but set by us. Can be done however we want

**Comment by coledeb** [comment]
Yeah of course @ThePjpollie We would have complete control over making / editing the titles, the only thing a user could do is choose to set it as it works now. And yeah having a different bot that reads / updates the same DB as the main one would be ideal @HaydenMeloche

**Comment by HaydenMeloche** [comment]
yeah thats what im talking about. Way to much work to put the alphaconsole bot in a different server

**Comment by ThePjpollie** [comment]
What's the plan for this now? 
I should have some time coming up from next week on the start working on this?

**Comment by ThePjpollie** [comment]
^ Bump

**Comment by ThePjpollie** [comment]
Alright. I have an idea for this. Instead of writing it all out. I'll just create it. Once available I'll show you guys.

**Comment by ThePjpollie** [comment]
First version of this should be done and ready to go! 🎉 
Let me know if you wanna go over it :)

**Comment by ThePjpollie** [comment]
This should be good to go.

**Comment by ThePjpollie** [comment]
I'll be closing this since it's working as far as I'm aware :)
