### ISSUE TITLE
Line breaks on titles

### ISSUE THREAD

**Issue by Barbosicks** [AlphaConsole/AlphaConsoleBot#142]
Bot is allowing line breaks on titles which breaks the alphaconsole functionality and causes people to crash ingame. You should strip it from everything except Alphanumeric values before storing in db.

**Comment by Vezqi** [comment]
🤔

**Comment by coledeb** [comment]
https://cdn.discordapp.com/attachments/278336241114677258/414142126452899842/unknown.png

The error that causes people to crash. This affects every user in game with the player that has the title. It crashes if pressing `OK`.

**Comment by coledeb** [comment]
@Vezqi Rocket League

**Comment by Rexzyy** [comment]
Vezqi, clicking OK or the X causes Rocket League to close. This does not affect AC for the user.
He beat me in a 1v1 cause of this. :(

**Comment by Barbosicks** [comment]
Pretty sure he had disabled titles on his end or he would crash aswell.

**Comment by Vezqi** [comment]
Shall we do some testing?

**Comment by Rexzyy** [comment]
I'm positive he did, he made the remark that he had removed everything related to AC from his computer.

"Switch - Today at 1:13 PM
so, it seems like even after deleting all my alphaconsole files, i still make people crash if theyre using alphaconsole, any ideas whatsoever?"

**Comment by Barbosicks** [comment]
No testing required. We know what it is and how to fix. Just need the devs to stop being lazy.. or someone to pull request a fix 🤔

**Comment by Vezqi** [comment]
Ironic

**Comment by Rexzyy** [comment]
Iconic*

**Comment by HaydenMeloche** [comment]
removed as it  no longer is game breaking
