### ISSUE TITLE
!serverinfo doesn't work

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#147]
The `!serverinfo` command does not return anything.

**Comment by HaydenMeloche** [comment]
It works in the beta server but not our live server. I'm guessing it has something to do with it being a partner server.

**Comment by coledeb** [comment]
🤔 Could be

**Comment by ThePjpollie** [comment]
Yeah, working all fine on Test server. Would need to test on main server and receive the error log, most likely would find the error then. I'll temporary remove the emotes part since I assume it could be that being too long for an embed. So let's see if that'll work :)

**Comment by ThePjpollie** [comment]
lmao that other commit belonged to #150 ^ My bad

**Comment by ThePjpollie** [comment]
I still don't see why it's not working on the normal server. Always worked fine on Beta server...
I guess if possible I'll need the error to maybe find the problem. I tried removing Emoji's section but I have no clue what the problem could be

**Comment by HaydenMeloche** [comment]
fixed
