### ISSUE TITLE
Status counter bug & enhancements

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#150]
Setting the status to counter doesn't work if there are multiple statuses rotating. (IE setting status 1 to playing X and status 2 to playing counter)

Also, being able to set the counter to watching, streaming etc. would be cool. "Watching X members"

One final thought, @ThePjpollie what are your thoughts on having the counter being `members` vs `users`? I feel that `playing with X users` might be a better word for what our bot / discord is used for and is shorter as a status overall.

**Comment by ThePjpollie** [comment]
Alright I tried something. Not sure if this will fix it but worth a shot.
How it works now: 

If you do: `!status add WATCHING counter Users` then it'll replace counter to the actual counter.
Keep in mind counter needs to be all lowercase. You can make it how you want ofcourse, like:
`!status add LISTENING to counter voices` for example. Just put counter where you want the number :)

**Comment by HaydenMeloche** [comment]
`!status add LISTENING to counter complaints`

**Comment by ThePjpollie** [comment]
That's all possible LUL

**Comment by ThePjpollie** [comment]
How's it been going?

**Comment by ThePjpollie** [comment]
Status bugging out when only 1 status is in the list on new cycle
