### ISSUE TITLE
Improve !betaids command

### ISSUE THREAD

**Issue by burnss9** [AlphaConsole/AlphaConsoleBot#159]
pls

**Comment by ThePjpollie** [comment]
Wait did I fully forget about that? Shit, will do soon

**Comment by ThePjpollie** [comment]
How would you like it to be improved exactly?

**Comment by burnss9** [comment]
there are over 200 subs and only 81 ids get returned 🤔 
i propose that you search the db for the steam ids of all discord users with the role and union with the signed up members and union with a permanent staff id list and return all the uniques

feel free to have a better idea than that one, but i think iterating over the users to search the db would be effective, even if it was just a local copy of the db

**Comment by HaydenMeloche** [comment]
I like that ^
That would remove the sign up process entirely.

**Comment by HaydenMeloche** [comment]
Although can we fetch every user with a role?

**Comment by burnss9** [comment]
not sure :(

**Comment by ThePjpollie** [comment]
I'll unassign myself from this then. Since I rather keep the database of AC itself related to Root.
I have not looked into it and since it's related to the program and I rather leave it to you guys :)
