### ISSUE TITLE
Streaming status for bot

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#164]
I talked with root about this in the past, but it would be cool if there was an API or some way for the bot to automatically update its status with " `STREAMING` at .tv/AlphaConsole " or " `STREAMING` live at .tv/AlphaConsole " ... some variation of that whenever a member of our stream team goes live.  Not sure if that is even possible, but would be good to look into

**Comment by ThePjpollie** [comment]
I know it's possible. Just discussing the best way:

@HaydenMeloche As far as I know Twitch does not have an event handler to trigger on when going live.
Best option that I could think of is polling the API every 5 minutes and checking the status?

**Comment by HaydenMeloche** [comment]
@ThePjpollie I got a twitch api working :+1:
