### ISSUE TITLE
Move twitch sub reset message

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#172]
It might be better to have the embed saying that X user's color was reset because their subscription ended moved to the `#ac-log` channel instead of `#mod-log` how it is currently. Not really relevant to other moderation issues.

**Comment by HaydenMeloche** [comment]
00c5cea06539d78c8e437c52a29bb9a6b96c0d47

**Comment by HaydenMeloche** [comment]
I can't properly type numbers apparently
