### ISSUE TITLE
Bot announcement feature

### ISSUE THREAD

**Issue by HaydenMeloche** [AlphaConsole/AlphaConsoleBot#175]
![image](https://user-images.githubusercontent.com/15106748/39094454-9d7c5590-45fd-11e8-84d3-2673d22a085f.png)

**Comment by ThePjpollie** [comment]
I have made a function in the newMessage event file completely at the bottom called `postPin`.
It can easily be added to other places for this purpose. Not installing it until I have more info on when to use and how to be set up :)

**Comment by ThePjpollie** [comment]
Will be closing due to innactivity. Will re-open if new suggestions comes up.
