### ISSUE TITLE
Send a message to a channel indicating that someone has subscribed to the Twitch

### ISSUE THREAD

**Issue by Vezqi** [AlphaConsole/AlphaConsoleBot#177]
I think would be neat if we had the bot send a message to a new channel named `#sub-log`, or something related which sends a message with the user that subbed, the tier, etc...

This is an example of how the RichEmbed could look: 

![image](https://user-images.githubusercontent.com/27045730/39213265-f0c1c00e-47c5-11e8-9414-ed36cf9de9a7.png)

**Comment by coledeb** [comment]
This would be a good idea, I don't think we need a new channel for it though, rather place it in `#ac-log` like #172 Perhaps add a total count of twitch subs to the bottom of this embed and the "title reset because subscription ended" embed?

**Comment by coledeb** [comment]
I don't think a new channel is required because we already have 4 log channels in the server, 5 might be a bit much but if the spam from this would be too much for `#ac-log` then a 5th channel could be considered.
![mcitb1v](https://user-images.githubusercontent.com/27379200/39262129-22f1cec0-4884-11e8-9795-7681a0352403.png)

**Comment by Vezqi** [comment]
That's actually a better idea.

**Comment by ThePjpollie** [comment]
This is currently what I build in.
![discord_2018-05-02_02-09-47](https://user-images.githubusercontent.com/12276548/39499400-e770301a-4dad-11e8-92d2-b6113f8bfb85.png)

This is based on their "Twitch Sub" role in Discord. This way there is no new API call to reduce load on the bot. But this way I'm not able to detect which tier neither can we see if they subbed without their Discord linked.

This is a start. I might look into using the Twitch API for a detailed version. If we eventually switch to Twitch API we'll NOT be able to tag the new sub, I'll only be able to provide you the Twitch Name.
