### ISSUE TITLE
Add a constant message to the bottom of channels such as #suggestions & #showcase

### ISSUE THREAD

**Issue by Mazzerss** [AlphaConsole/AlphaConsoleBot#180]
We constantly get the same suggestions & showcase mistakes/rule violations because people don't read the pins and/or channel topic. If we added a constant message from the bot at the bottom of the channel that deletes and reposts itself every time someone messages/a message gets deleted it would take a workload off the people forced to clear the channel out. Even something like *Make sure to read the pins before sending a message here!* would help and it shouldn't be too difficult to implement.

**Comment by ThePjpollie** [comment]
Seems like not working on live bot :(

**Comment by ThePjpollie** [comment]
This is working in suggestions. I temporarily disabled it in Showcase since there is no pin in there.
Re-open or DM me to enable it again.
