### ISSUE TITLE
Overridden titles indicator

### ISSUE THREAD

**Issue by burnss9** [AlphaConsole/AlphaConsoleBot#185]
DB column for "TitleOverridden" could be added to help differentiate people who we have set blacklisted titles for. Would only work on future ones but I think it'd be helpful

**Comment by HaydenMeloche** [comment]
👍

**Comment by HaydenMeloche** [comment]
On the topic of this, maybe keep track of how many times someone triggers the blacklist. If they trigger it to many times then notify a staff member.

**Comment by ThePjpollie** [comment]
I currently save all titles that people get reported for if staff / users use the new feature in Discord.

We could also detec how many times they triggered the blacklist checker, how would you take this?
Like check for x amount of time, if he passed the limit log all title he tried in a message to provide to staff?

**Comment by ThePjpollie** [comment]
Also fixed. **All** titles (blacklisted or not) are saved within database and can be checked at anytime on the Staff Panel. If the bot marked the title as blacklisted they'll show up in red on the site.
