### ISSUE TITLE
Prevent command conflicts

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#187]
Commands are able to be created using `!addcom` that contain the same trigger as `!checkdb`, `!update` and all existing commands (potentially including ones already created by `!addcom` as well), leading to conflicts and those commands either not working or both running.  A check should be added that denies the creation and returns an embed or some form of feedback when attempting to create a command that is already existent in the bot either as a permanent command or as an `!addcom` created command.

**Comment by ThePjpollie** [comment]
We have mentioned in the past why we didn't do that: It's a staff command, I assume you can trust staff. That's why we aren't doing as much safety checks as on User-based commands.

But if it's necessary then sure.

**Comment by coledeb** [comment]
Yeah its not necessary because I don't trust them, rather an `!update` command has been created twice because people forgot or were unaware that this was a command. Regardless it probably would be good to have checks for safety / standard practices either way.
