### ISSUE TITLE
Using commands in DM

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#195]
This is an expansion of the idea suggested in #163. Using commands in DM with the bot, from muting to overriding titles, to looking up cases could clean up channels in the server while still logging all (already logged) actions taken to the log channels for the sake of transparency and accountability. This would also remove possible conflicts with Discord's tagging system while tagging users or attempting to override titles for example.

**Comment by ThePjpollie** [comment]
It would be kind off a mess having to make everything possible in DMs to.
I do agree with having override in DMs + having less commands to read stuff.

I think those 2 are getting resolved.
- Overriding is now possible in DMs
- To read or find info of cases this will all eventually be possible on Staff Panel along with much other things. I'm just not sure if staff is interested in doing that effort to start their browser and such.. :I

**Comment by ThePjpollie** [comment]
Will be closing due to innactivity. Will re-open if new suggestions comes up.
