### ISSUE TITLE
Temporary beta role, which lasts 30 days.

### ISSUE THREAD

**Issue by Vezqi** [AlphaConsole/AlphaConsoleBot#205]
I've come across a few users that accidentally sub to the Twitch account that we are hosting, instead of subbing directly to AlphaConsole, which makes it so that they don't get beta access. I understand completely that this is not our problem, but it makes our CX look better, IMO. Note, that I could see how this could be a possibly abused feature, but read below:

- What I'm thinking is a role, that when assigned by a command, will expire after 30 days?

- For Support/Staff, if someone runs into this issue, ask that they send a screenshot of https://twitch.tv/subscriptions, and if it shows they subbed to the user we were hosting at the time, then we (preferably Mod +) can assign the role, and let them know? I think that if we ask them to send a screenshot of their subscriptions page, and it checks out, it will make it less likely for someone to bypass this and scam us for free beta access. 

Doing something like `!beta <user mention>` or `!beta <user id>` will grant them the role, and send them a message saying something like it does when they get their sub role, but instead apologize for the confusion, say that this a one time offer for the inconvenience, and explain how they can correctly sub to the Twitch next time?

**Comment by Barbosicks** [comment]
I'll "inconviently" sub to other guy on purpose.. Yikes. 

No, thanks.
