### ISSUE TITLE
Suggestion: Adding the ID of the user to ServerLog channel

### ISSUE THREAD

**Issue by Granatenei** [AlphaConsole/AlphaConsoleBot#235]
Example:
Before:
Channel: #general Granatenei#0001's message was deleted. Content: I blame Cole
After:
Channel: #general Granatenei#0001's (156146475884216321) message was deleted. Content: I blame Cole
Reason:
If you have the id its easier to tag people for other commands etc.
Using the name instead of <@!156146475884216321> sometimes tags the wrong person....

**Comment by ThePjpollie** [comment]
That's only in message removals right? Other event messages should show the ID. I don't know why I didnt add the ID to message removals. Will fix soon!

PS: Thank you very much for creating an issue instead of DM'ing. Makes the fix procedure much easier :kissing_heart:

**Comment by Granatenei** [comment]
You have the id in the "mod-log" but not the "server-log" unless I am blind.

No worries, I figured it would be helpful to have the suggestion in here
