### ISSUE TITLE
Adding a Blacklist section to the site

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#238]
Basically the title, right now I'm shooting in the dark when I attempt to figure out why a random title is blacklisted.  I know @ThePjpollie you mentioned you will have a feature about highlighting the issue, but having a web panel to view the entire list, and preferably make modifications (additions and removal) would be nice as well if possible.  Not sure if staff role or mod role should be the minimum for this, leaning towards staff but not 100% and we can decide that later if this is implemented.

**Comment by ThePjpollie** [comment]
I'll make it read-only for staff. New, edit and removals for admins

**Comment by coledeb** [comment]
Sounds perfect.

**Comment by ThePjpollie** [comment]
Uh yeah, update on this: It's already live LUL, but blacklist page is live.
Title checker soonTM

**Comment by ThePjpollie** [comment]
First version of it is now online :) 
Improvements soonTM

**Comment by ThePjpollie** [comment]
This should be done. Completely forgot about this.

Feedback welcome! Closing this for now :)
