### ISSUE TITLE
Reactions on a command sent by a support can be run

### ISSUE THREAD

**Issue by evilpauwse1** [AlphaConsole/AlphaConsoleBot#322]
3 supports required/1 mod

**Comment by burnss9** [comment]
Make Joey worth 2 for real

**Comment by evilpauwse1** [comment]
Make sure to go back through mod commands and add in testing for the message process

**Comment by nitrog0d** [comment]
I agree with cat

**Comment by evilpauwse1** [comment]
Allow for message returns including if it was approved or blocked with the message link.
