### ISSUE TITLE
Automatically resetting title of an ex-twitch sub

### ISSUE THREAD

**Issue by coledeb** [AlphaConsole/AlphaConsoleBot#46]
@HaydenMeloche This would be a good idea as a feature.  If someone loses the twitch sub role, have the bot reset their title so that they can't use the colors if they still have them.

Depending on the capabilities of this, maybe even have it check their title automatically, and only reset the color if it is 2 or 6, and only reset the title if it is the "AlphaConsole Twitch Sub" special title.

**Comment by ThePjpollie** [comment]
People's color get reset no matter what. Even when they are also Legacy.
I assume Legacy has the same rights as sub?

So maybe need a check if the user is Legacy. If so, don't change color?
