### ISSUE TITLE
Stats in bot

### ISSUE THREAD

**Issue by ThePjpollie** [AlphaConsole/AlphaConsoleBot#49]
Save the stats of 
- Members joining
- Members leaving
- Total messages send
  = Make a different counter for titles & all other channels
  = Ignore all the log channels for the other channels.

**Comment by JonasPardon** [comment]
Did someone say statbot?

**Comment by ThePjpollie** [comment]
Going to close this. Like I mentioned to the statbot maker ^:
I'll never be able to make a such detailed & sophisticated bot as a bot specifically made for that.
And as far as I've seen it's been working good & liked by the staff
